### ISSUE TITLE
What is the name of this algorithm

### ISSUE THREAD

**Issue by dvberkel** [HAN-ASD-DT/sorting-assignment-Skudoku#1]
I would like to know the name of this sorting algorithm. Can you find a reference to a description of this algorithm?

**Comment by Skudoku** [comment]
Will look into this.

**Comment by Skudoku** [comment]
This is bubble sort, looking at the if statement,

```
if (rhs > lhs) {
                    inputList.set(end, lhs);
                    inputList.set(start, rhs);
                }
```

It's checking it's neighbor if it's bigger than the other and set to the corresponding spot.
